# Questions I can ask from this Data
1. Which country has the highest number of Terror Attacks?
2. What is the most used weapon?
3. Which target groups were most attacked?
4. Which perpertrator groups have the highest number of attacks?
5. Frequency of Terrorist incidents over years
6. Distribution of Casualities
7. What are the most common types of Terrorist attacks?

In [211]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import chardet

In [212]:
with open('globalterrorismdb_0718dist.csv', 'rb') as f:
    encoding = chardet.detect(f.read())['encoding']

In [213]:
df = pd.read_csv('globalterrorismdb_0718dist.csv', encoding=encoding)

/var/folders/nq/j6_w6klj0yd9h2kwhxzcbyhm0000gn/T/ipykernel_75203/43825309.py:1: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('globalterrorismdb_0718dist.csv', encoding=encoding)

In [214]:
df.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [215]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Columns: 135 entries, eventid to related
dtypes: float64(55), int64(22), object(58)
memory usage: 187.1+ MB

In [216]:
df.describe()

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,...,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,1.816910e+05,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,181691.000000,177135.000000,1.771340e+05,181685.000000,...,1.350000e+03,5.630000e+02,7.740000e+02,552.000000,10991.000000,10400.000000,181691.000000,181691.000000,181691.000000,181691.000000
mean,2.002705e+11,2002.638997,6.467277,15.505644,0.045346,131.968501,7.160938,23.498343,-4.586957e+02,1.451452,...,3.172530e+06,5.784865e+05,7.179437e+05,240.378623,4.629242,-29.018269,-4.543731,-4.464398,0.090010,-3.945952
std,1.325957e+09,13.259430,3.388303,8.814045,0.208063,112.414535,2.933408,18.569242,2.047790e+05,0.995430,...,3.021157e+07,7.077924e+06,1.014392e+07,2940.967293,2.035360,65.720119,4.543547,4.637152,0.568457,4.691325
min,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,4.000000,1.000000,-53.154613,-8.618590e+07,1.000000,...,-9.900000e+01,-9.900000e+01,-9.900000e+01,-99.000000,1.000000,-99.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,1.991021e+11,1991.000000,4.000000,8.000000,0.000000,78.000000,5.000000,11.510046,4.545640e+00,1.000000,...,0.000000e+00,0.000000e+00,-9.900000e+01,0.000000,2.000000,-99.000000,-9.000000,-9.000000,0.000000,-9.000000
50%,2.009022e+11,2009.000000,6.000000,15.000000,0.000000,98.000000,6.000000,31.467463,4.324651e+01,1.000000,...,1.500000e+04,0.000000e+00,0.000000e+00,0.000000,4.000000,0.000000,-9.000000,-9.000000,0.000000,0.000000
75%,2.014081e+11,2014.000000,9.000000,23.000000,0.000000,160.000000,10.000000,34.685087,6.871033e+01,1.000000,...,4.000000e+05,0.000000e+00,1.273412e+03,0.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,2.017123e+11,2017.000000,12.000000,31.000000,1.000000,1004.000000,12.000000,74.633553,1.793667e+02,5.000000,...,1.000000e+09,1.320000e+08,2.750000e+08,48000.000000,7.000000,2769.000000,1.000000,1.000000,1.000000,1.000000

### Selecting Relevant Columns for the visualizations

In [217]:
sub = ['eventid', 'iyear','imonth', 'iday', 'country_txt', 'city', 'latitude', 'longitude', 'attacktype1_txt', 'targtype1_txt', 'targsubtype1_txt', 'gname', 'weaptype1_txt', 'weapsubtype1_txt']
df2 = df[sub]

In [218]:
df2.head()

,eventid,iyear,imonth,iday,country_txt,city,latitude,longitude,attacktype1_txt,targtype1_txt,targsubtype1_txt,gname,weaptype1_txt,weapsubtype1_txt
0,197000000001,1970,7,2,Dominican Republic,Santo Domingo,18.456792,-69.951164,Assassination,Private Citizens & Property,Named Civilian,MANO-D,Unknown,NaN
1,197000000002,1970,0,0,Mexico,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",23rd of September Communist League,Unknown,NaN
2,197001000001,1970,1,0,Philippines,Unknown,15.478598,120.599741,Assassination,Journalists & Media,Radio Journalist/Staff/Facility,Unknown,Unknown,NaN
3,197001000002,1970,1,0,Greece,Athens,37.997490,23.762728,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,Unknown,Explosives,Unknown Explosive Type
4,197001000003,1970,1,0,Japan,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,Government (Diplomatic),Embassy/Consulate,Unknown,Incendiary,NaN

In [219]:
df2.isnull().sum()

eventid                 0
iyear                   0
imonth                  0
iday                    0
country_txt             0
city                  435
latitude             4556
longitude            4557
attacktype1_txt         0
targtype1_txt           0
targsubtype1_txt    10373
gname                   0
weaptype1_txt           0
weapsubtype1_txt    20768
dtype: int64

In [220]:
df2 = df2.dropna()

In [221]:
df2.isnull().sum()

eventid             0
iyear               0
imonth              0
iday                0
country_txt         0
city                0
latitude            0
longitude           0
attacktype1_txt     0
targtype1_txt       0
targsubtype1_txt    0
gname               0
weaptype1_txt       0
weapsubtype1_txt    0
dtype: int64

In [222]:
df2.head()

,eventid,iyear,imonth,iday,country_txt,city,latitude,longitude,attacktype1_txt,targtype1_txt,targsubtype1_txt,gname,weaptype1_txt,weapsubtype1_txt
3,197001000002,1970,1,0,Greece,Athens,37.997490,23.762728,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,Unknown,Explosives,Unknown Explosive Type
5,197001010002,1970,1,1,United States,Cairo,37.005105,-89.176269,Armed Assault,Police,"Police Building (headquarters, station, school)",Black Nationalists,Firearms,Unknown Gun Type
6,197001020001,1970,1,2,Uruguay,Montevideo,-34.891151,-56.187214,Assassination,Police,Police Security Forces/Officers,Tupamaros (Uruguay),Firearms,Automatic or Semi-Automatic Rifle
7,197001020002,1970,1,2,United States,Oakland,37.791927,-122.225906,Bombing/Explosion,Utilities,Electricity,Unknown,Explosives,Unknown Explosive Type
8,197001020003,1970,1,2,United States,Madison,43.076592,-89.412488,Facility/Infrastructure Attack,Military,Military Recruiting Station/Academy,New Year's Gang,Incendiary,Molotov Cocktail/Petrol Bomb

In [223]:
df2.shape

(147803, 14)

In [224]:
df2.head(100)

,eventid,iyear,imonth,iday,country_txt,city,latitude,longitude,attacktype1_txt,targtype1_txt,targsubtype1_txt,gname,weaptype1_txt,weapsubtype1_txt
3,197001000002,1970,1,0,Greece,Athens,37.997490,23.762728,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,Unknown,Explosives,Unknown Explosive Type
5,197001010002,1970,1,1,United States,Cairo,37.005105,-89.176269,Armed Assault,Police,"Police Building (headquarters, station, school)",Black Nationalists,Firearms,Unknown Gun Type
6,197001020001,1970,1,2,Uruguay,Montevideo,-34.891151,-56.187214,Assassination,Police,Police Security Forces/Officers,Tupamaros (Uruguay),Firearms,Automatic or Semi-Automatic Rifle
7,197001020002,1970,1,2,United States,Oakland,37.791927,-122.225906,Bombing/Explosion,Utilities,Electricity,Unknown,Explosives,Unknown Explosive Type
8,197001020003,1970,1,2,United States,Madison,43.076592,-89.412488,Facility/Infrastructure Attack,Military,Military Recruiting Station/Academy,New Year's Gang,Incendiary,Molotov Cocktail/Petrol Bomb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,197003040002,1970,3,4,United States,Martinez,38.019304,-122.134062,Bombing/Explosion,Transportation,Train/Train Tracks/Trolley,Unknown,Explosives,Dynamite/TNT
108,197003040003,1970,3,4,United States,Denver,39.758968,-104.876305,Bombing/Explosion,Private Citizens & Property,Vehicles/Transportation,Left-Wing Militants,Explosives,Dynamite/TNT
109,197003050001,1970,3,5,United States,Seattle,47.610786,-122.331306,Bombing/Explosion,Government (General),Government Building/Facility/Office,Left-Wing Militants,Explosives,Dynamite/TNT
110,197003050002,1970,3,5,United States,Denver,39.758968,-104.876305,Bombing/Explosion,Private Citizens & Property,Vehicles/Transportation,Left-Wing Militants,Explosives,Dynamite/TNT
111,197003050003,1970,3,5,United States,San Juan,18.386932,-66.061127,Assassination,Military,"Military Personnel (soldiers, troops, officers...",Armed Commandos of Liberation,Firearms,Unknown Gun Type

In [225]:
df2.count()

eventid             147803
iyear               147803
imonth              147803
iday                147803
country_txt         147803
city                147803
latitude            147803
longitude           147803
attacktype1_txt     147803
targtype1_txt       147803
targsubtype1_txt    147803
gname               147803
weaptype1_txt       147803
weapsubtype1_txt    147803
dtype: int64

In [226]:
df2.dtypes

eventid               int64
iyear                 int64
imonth                int64
iday                  int64
country_txt          object
city                 object
latitude            float64
longitude           float64
attacktype1_txt      object
targtype1_txt        object
targsubtype1_txt     object
gname                object
weaptype1_txt        object
weapsubtype1_txt     object
dtype: object

In [227]:
df2.head()

,eventid,iyear,imonth,iday,country_txt,city,latitude,longitude,attacktype1_txt,targtype1_txt,targsubtype1_txt,gname,weaptype1_txt,weapsubtype1_txt
3,197001000002,1970,1,0,Greece,Athens,37.997490,23.762728,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,Unknown,Explosives,Unknown Explosive Type
5,197001010002,1970,1,1,United States,Cairo,37.005105,-89.176269,Armed Assault,Police,"Police Building (headquarters, station, school)",Black Nationalists,Firearms,Unknown Gun Type
6,197001020001,1970,1,2,Uruguay,Montevideo,-34.891151,-56.187214,Assassination,Police,Police Security Forces/Officers,Tupamaros (Uruguay),Firearms,Automatic or Semi-Automatic Rifle
7,197001020002,1970,1,2,United States,Oakland,37.791927,-122.225906,Bombing/Explosion,Utilities,Electricity,Unknown,Explosives,Unknown Explosive Type
8,197001020003,1970,1,2,United States,Madison,43.076592,-89.412488,Facility/Infrastructure Attack,Military,Military Recruiting Station/Academy,New Year's Gang,Incendiary,Molotov Cocktail/Petrol Bomb

### Renaming Columns

In [228]:
df2.rename(columns={'iyear': 'year', 'imonth':'month', 'iday':'day', 'country_txt': 'country', 'attacktype1_txt':'attacktype', 'targtype1_txt': 'targtype', 'targsubtype1_txt': 'targsubtype', 'gname': 'pgroup', 'weaptype1_txt': 'weaptype', 'weapsubtype1_txt': 'weapsubtype'}, inplace=True)

In [229]:
df2.head()

,eventid,year,month,day,country,city,latitude,longitude,attacktype,targtype,targsubtype,pgroup,weaptype,weapsubtype
3,197001000002,1970,1,0,Greece,Athens,37.997490,23.762728,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,Unknown,Explosives,Unknown Explosive Type
5,197001010002,1970,1,1,United States,Cairo,37.005105,-89.176269,Armed Assault,Police,"Police Building (headquarters, station, school)",Black Nationalists,Firearms,Unknown Gun Type
6,197001020001,1970,1,2,Uruguay,Montevideo,-34.891151,-56.187214,Assassination,Police,Police Security Forces/Officers,Tupamaros (Uruguay),Firearms,Automatic or Semi-Automatic Rifle
7,197001020002,1970,1,2,United States,Oakland,37.791927,-122.225906,Bombing/Explosion,Utilities,Electricity,Unknown,Explosives,Unknown Explosive Type
8,197001020003,1970,1,2,United States,Madison,43.076592,-89.412488,Facility/Infrastructure Attack,Military,Military Recruiting Station/Academy,New Year's Gang,Incendiary,Molotov Cocktail/Petrol Bomb

### For some of the events the date of the actual event is unknown therefore just going ahead with month and the year column

In [230]:
df2 = df2.drop(df2[df2['month']==0].index)
df2 = df2.drop(df2[df2['day']==0].index)

In [231]:
position = 4
new_column = df2['year'].astype(str) + '/' + df2['month'].astype(str) + '/' + df2['day'].astype(str)
df2.insert(position, 'date', new_column)

In [232]:
df2.head()

,eventid,year,month,day,date,country,city,latitude,longitude,attacktype,targtype,targsubtype,pgroup,weaptype,weapsubtype
5,197001010002,1970,1,1,1970/1/1,United States,Cairo,37.005105,-89.176269,Armed Assault,Police,"Police Building (headquarters, station, school)",Black Nationalists,Firearms,Unknown Gun Type
6,197001020001,1970,1,2,1970/1/2,Uruguay,Montevideo,-34.891151,-56.187214,Assassination,Police,Police Security Forces/Officers,Tupamaros (Uruguay),Firearms,Automatic or Semi-Automatic Rifle
7,197001020002,1970,1,2,1970/1/2,United States,Oakland,37.791927,-122.225906,Bombing/Explosion,Utilities,Electricity,Unknown,Explosives,Unknown Explosive Type
8,197001020003,1970,1,2,1970/1/2,United States,Madison,43.076592,-89.412488,Facility/Infrastructure Attack,Military,Military Recruiting Station/Academy,New Year's Gang,Incendiary,Molotov Cocktail/Petrol Bomb
9,197001030001,1970,1,3,1970/1/3,United States,Madison,43.072950,-89.386694,Facility/Infrastructure Attack,Government (General),Government Building/Facility/Office,New Year's Gang,Incendiary,Gasoline or Alcohol

In [233]:
df2['date'] = pd.to_datetime(df2['date'])

In [234]:
df2.columns

Index(['eventid', 'year', 'month', 'day', 'date', 'country', 'city',
       'latitude', 'longitude', 'attacktype', 'targtype', 'targsubtype',
       'pgroup', 'weaptype', 'weapsubtype'],
      dtype='object')

In [235]:
df2.to_csv('Global Terrorism Cleaned.csv', index=False)

In [236]:
df2.groupby(['country'])['eventid'].size()

country
Afghanistan    10010
Albania           68
Algeria         2163
Angola           386
Argentina        613
               ...
Yemen           2559
Yugoslavia       186
Zaire             27
Zambia            51
Zimbabwe          75
Name: eventid, Length: 201, dtype: int64

In [237]:
df2

,eventid,year,month,day,date,country,city,latitude,longitude,attacktype,targtype,targsubtype,pgroup,weaptype,weapsubtype
5,197001010002,1970,1,1,1970-01-01,United States,Cairo,37.005105,-89.176269,Armed Assault,Police,"Police Building (headquarters, station, school)",Black Nationalists,Firearms,Unknown Gun Type
6,197001020001,1970,1,2,1970-01-02,Uruguay,Montevideo,-34.891151,-56.187214,Assassination,Police,Police Security Forces/Officers,Tupamaros (Uruguay),Firearms,Automatic or Semi-Automatic Rifle
7,197001020002,1970,1,2,1970-01-02,United States,Oakland,37.791927,-122.225906,Bombing/Explosion,Utilities,Electricity,Unknown,Explosives,Unknown Explosive Type
8,197001020003,1970,1,2,1970-01-02,United States,Madison,43.076592,-89.412488,Facility/Infrastructure Attack,Military,Military Recruiting Station/Academy,New Year's Gang,Incendiary,Molotov Cocktail/Petrol Bomb
9,197001030001,1970,1,3,1970-01-03,United States,Madison,43.072950,-89.386694,Facility/Infrastructure Attack,Government (General),Government Building/Facility/Office,New Year's Gang,Incendiary,Gasoline or Alcohol
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181685,201712310020,2017,12,31,2017-12-31,Afghanistan,Maymana,35.921051,64.774544,Bombing/Explosion,Business,Retail/Grocery/Bakery,Unknown,Explosives,Unknown Explosive Type
181686,201712310022,2017,12,31,2017-12-31,Somalia,Ceelka Geelow,2.359673,45.385034,Armed Assault,Military,Military Checkpoint,Al-Shabaab,Firearms,Unknown Gun Type
181687,201712310029,2017,12,31,2017-12-31,Syria,Jableh,35.407278,35.942679,Bombing/Explosion,Military,Military Barracks/Base/Headquarters/Checkpost,Muslim extremists,Explosives,"Projectile (rockets, mortars, RPGs, etc.)"
181688,201712310030,2017,12,31,2017-12-31,Philippines,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,Private Citizens & Property,House/Apartment/Residence,Bangsamoro Islamic Freedom Movement (BIFM),Incendiary,Arson/Fire
181689,201712310031,2017,12,31,2017-12-31,India,Imphal,24.798346,93.940430,Bombing/Explosion,Government (General),Government Building/Facility/Office,Unknown,Explosives,Grenade

In [241]:
df2.value_counts('weaptype')

weaptype
Explosives    83155
Firearms      54713
Incendiary     5923
Melee          3377
Chemical        139
Other             1
Name: count, dtype: int64

In [240]:
df2.value_counts('weapsubtype')

weapsubtype
Unknown Explosive Type                       40160
Unknown Gun Type                             31655
Automatic or Semi-Automatic Rifle            15618
Projectile (rockets, mortars, RPGs, etc.)     9433
Vehicle                                       8930
Handgun                                       6226
Other Explosive Type                          6152
Grenade                                       4896
Arson/Fire                                    3942
Landmine                                      3626
Suicide (carried bodily by human being)       2878
Remote Trigger                                2459
Knife or Other Sharp Object                   2405
Sticky Bomb                                   1550
Molotov Cocktail/Petrol Bomb                  1190
Dynamite/TNT                                  1159
Rifle/Shotgun (non-automatic)                 1134
Gasoline or Alcohol                            791
Time Fuse                                      701
Blunt Object                                   554
Pipe Bomb                                      520
Letter Bomb                                    490
Hands, Feet, Fists                             219
Pressure Trigger                               201
Unknown Weapon Type                             99
Rope or Other Strangling Device                 93
Other Gun Type                                  80
Poisoning                                       78
Explosive                                       61
Suffocation                                      8
Name: count, dtype: int64